routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\ElectricityController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ClientDetailController;
use App\Http\Controllers\MaintenanceController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\BuildingController;
use App\Http\Controllers\AreaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::get('/ajax/cancel_booking', [HomeController::class, 'getCancelBooking']);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    // Admin Setting
    Route::resource('roles', RoleController::class)->names([
        'index' => 'admin.roles.index',
        'create' => 'admin.roles.create',
        'edit' => 'admin.roles.edit',
        'destroy' => 'admin.roles.destroy',
        // Add other routes if needed
    ]);
    Route::resource('users', UserController::class)->names([
        'index' => 'admin.users.index',
        'create' => 'admin.users.create',
        // Add other routes if needed
    ]);
    Route::resource('permissions', PermissionController::class)->names([
        'index' => 'admin.permissions.index',
        'create' => 'admin.permissions.create',
        // Add other routes if needed
    ]);
    Route::resource('rooms', RoomController::class)->names([
        'index' => 'admin.rooms.index',
        'create' => 'admin.rooms.create',
    ]);
    Route::resource('electricities', ElectricityController::class);
    Route::resource('clients', ClientController::class);
    Route::post('checkout-client', [ClientController::class,'checkout'])->name('checkout-client');
    Route::resource('client-details', ClientDetailController::class);
    Route::resource('maintenances', MaintenanceController::class);
    Route::resource('expenses', ExpenseController::class);
    Route::resource('areas', AreaController::class);
    Route::resource('buildings', BuildingController::class);
    Route::get('client-details-create/{id}', [ClientDetailController::class,'billing'])->name('client-details-create');
    Route::get('client-details-view/{id}', [ClientDetailController::class,'billingDetail'])->name('client-details-view');
    Route::get('client-details-download/{id}', [ClientDetailController::class,'billingDownload'])->name('client-details-download');
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
    Route::get('/calculate-eb-amount', [ClientDetailController::class, 'calculateEbAmount'])->name('calculate.eb.amount');

    // End Admin Setting
});

app/Models/Electricity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Electricity extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'property_id',
        'unit',
        'amount',
        'created_by',
        'status'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'deleted_at' => 'datetime',
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ElectricityController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Electricity;
use App\Models\User;
use Spatie\Permission\Models\Permission;
use DB;
use Auth;

class ElectricityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:eb-list');
         $this->middleware('permission:eb-create', ['only' => ['create','store']]);
         $this->middleware('permission:eb-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:eb-delete', ['only' => ['destroy']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user   = Auth::user();
        // $query  = Electricity::withTrashed()->orderBy('id','DESC');
        $query  = Electricity::orderBy('id','DESC');
        if(isset($request->search))
        {
            if(isset($request->fromdate))
            {
                if($request->fromdate!=""){
                    $Sindate= date("Y-m-d", strtotime($request->fromdate));
                    $query->where('electricities.created_at','>=',$Sindate);
                } 
            }
            if(isset($request->todate))
            {
                if($request->todate!=""){
                    $Todate= date("Y-m-d", strtotime($request->todate. ' +1 day'));
                    $query->where('electricities.created_at','<=',$Todate);
                }  
            }
           
            if($request->name)
            {
                $name=$request->name;
                $query->where('electricities.name','like', '%'.$name.'%');
            }
        }
        $electricities = $query->paginate(20);
        return view('admin.electricities.index',compact('electricities','request'))
            ->with('i', ($request->input('page', 1) - 1) * 20);
       
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.electricities.create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'      => 'required|unique:electricities,name',
            'amount'    => 'required|digits_between:1,10', // adjust 10 to the maximum length you need
        ]);
        $inputs                 =   $request->all();
        $inputs['created_by']   =   Auth::user()->id;
        $inputs['property_id']  =   Auth::user()->property_id;
        $electricities          =   Electricity::create($inputs);
        return redirect()->route('electricities.index')->with('success','Electricity created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $electricity               =   Electricity::find($id);
        return view('admin.electricities.index',compact('electricity'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $electricity    =   Electricity::find($id);
        $user           =   User::pluck('name','id');
        return view('admin.electricities.edit',compact('electricity','user'));
        
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'      => 'required|unique:electricities,name,' . $id,
            'amount'    => 'required|digits_between:1,10', // Adjust based on your requirements
        ]);
        $electricity           =   Electricity::findOrFail($id);
        $electricity->name     =   $request->input('name');
        $electricity->amount   =   $request->input('amount');
        $electricity->status   =   $request->input('status');
        $electricity->save();
        return redirect()->route('electricities.index')->with('success', 'Electricity updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Electricity $electricity)
    {
        $electricity->delete();
        return redirect()->route('electricities.index')->with('success','Electricity deleted successfully');
        
    }
}

resources/views/admin/electricities/create.blade.php
@extends('layouts.master') @php $page_title = 'Electricity Booking'; $page_name = 'Electricity Booking'; @endphp @section('css')
<link rel="stylesheet" href="{{ asset('assets/css/datepicker.min.css') }}" />
@endsection @section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <!-- <h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.
        </p> -->

    <!-- DataTales Example -->
    @if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">Add Electricity</h6>
            <a href="{{ route('electricities.index') }}">
                <button type="button" class="btn btn-danger" id="cancelButton">Back</button>
            </a>
        </div>
        <div class="card-body">
            <form method="POST" action="{{ route('electricities.store') }}" id="electricityCreation">
                @csrf
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="inputCity">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{old('name')}}" placeholder="Electricity Name"/>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputCity">Unit</label>
                        <input type="text" class="form-control" id="unit" name="unit" value="1" placeholder="Unit" readonly/>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputCity">Amount</label>
                        <input type="text" class="form-control" id="amount" name="amount" value="{{old('amount')}}" placeholder="Amount"/>
                    </div>
                </div>
               
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection @section('js')
<!-- Page level plugins -->

<!-- Page level custom scripts -->
<script src="{{ asset('assets/js/datepicker.min.js') }}"></script>
<script>
    $(document).ready(function () {
        $("#electricityCreation").validate({
            rules: {
                name: "required",
                amount: {
                    required: true,
                    digits: true,
                },
            },
            messages: {
                name: "Please Enter Name",
                amount: {
                    required: "This field is required",
                    digits: "Please enter only digits",
                },
            }
        });
    });
</script>
@endsection

resources/views/admin/electricities/edit.blade.php
@extends('layouts.master') @php $page_title = 'Electricity Booking'; $page_name = 'Electricity Booking'; @endphp @section('css')
<link rel="stylesheet" href="{{ asset('assets/css/datepicker.min.css') }}" />
@endsection @section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <!-- <h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.
        </p> -->

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">Edit Electricity</h6>
            <a href="{{ route('electricities.index') }}">
                <button type="button" class="btn btn-danger" id="cancelButton">Back</button>
            </a>
        </div>

        <div class="card-body">
            <form method="POST" action="{{ route('electricities.update', $electricity->id) }}" id="electricityCreation">
                @csrf @method('PUT')
                <input type="hidden" value="{{ $electricity->id }}" name="electricity_id" id="electricity_id" />
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="inputCity">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $electricity->name) }}" placeholder="Electricity Name" />
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputCity">Unit</label>
                        <input type="text" class="form-control" id="unit" name="unit" value="1" placeholder="Unit" readonly/>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputCity">Amount</label>
                        <input type="text" class="form-control" id="amount" name="amount" value="{{ old('amount', $electricity->amount) }}" placeholder="Amount" />
                    </div>
                </div>
                <div class="form-row">
                    @if($electricity->creted_by!='')
                        <div class="form-group col-md-4">
                            <label for="inputCity">Created By</label>
                            <input type="text" class="form-control"  value="{{$user[$electricity->creted_by] ?? ''}}" readonly/>
                        </div>
                    @endif
                    <div class="form-group col-md-4">
                        <label for="inputCity">Status</label>
                        <select name="status" class="form-control" id="status">
                            <option value="">--select Status--</option>
                            <option value="1" {{ old('status', $electricity->status ?? '') == "1" ? 'selected' : '' }}>Active</option>
                            <option value="2" {{ old('status', $electricity->status ?? '') == "2" ? 'selected' : '' }}>Inactive</option>
                        </select>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection @section('js')
<!-- Page level plugins -->
<script src="{{asset('assets/vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

<!-- Page level custom scripts -->
<script src="{{asset('assets/js/demo/datatables-demo.js')}}"></script>
<script src="{{ asset('assets/js/datepicker.min.js') }}"></script>
<script>
    $(document).ready(function () {
        $("#electricityCreation").validate({
            rules: {
                name: "required",
                amount: {
                    required: true,
                    digits: true,
                },
            },
            messages: {
                name: "Please Enter Name",
                amount: {
                    required: "This field is required",
                    digits: "Please enter only digits",
                },
            }
        });
    });
</script>
@endsection

resources/views/admin/electricities/index.blade.php
@extends('layouts.master') @php $page_title = 'All Electricity-List'; $page_name = 'All Electricity-List'; @endphp @section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <!-- <h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.
        </p> -->

    <!-- DataTales Example -->
    @if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">All Electricity</h6>
            <a href="{{ route('electricities.create') }}">
                <button type="button" class="btn btn-success" id="cancelButton">Add New</button>
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>S.no</th>
                            <th>Name</th>
                            <th>Unit</th>
                            <th>Amount</th>
                            <th>Status</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>S.no</th>
                            <th>Name</th>
                            <th>Unit</th>
                            <th>Amount</th>
                            <th>Status</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach($electricities as $electricity)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{$electricity->name ?? ''}}</td>
                            <td>{{$electricity->unit ?? ''}}</td>
                            <td>{{$electricity->amount ?? ''}}</td>
                            <td>{!! $electricity->status == 1 ? '<span class="badge bg-success">Active</span> ' :'<span class="badge bg-danger">InActive</span>' !!}</td>
                            <td>{{$electricity->created_at ? date('d M-y',strtotime($electricity->created_at)) : ''}}</td>
                            <td>
                                <a href="{{ route('electricities.edit',$electricity->id) }}" class="btn btn-warning btn-sm keychainify-checked"><i class="fas fa-pen-square fa-fw"></i></a>
                                {!! Form::open(['method' => 'DELETE','route' => ['electricities.destroy', $electricity->id],'style'=>'display:inline']) !!}
                                <button type="submit" style="border: 0px;" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-danger btn-sm"><i class="fas fa-trash fa-fw"></i></button>
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection @section('js')
<!-- Page level plugins -->
<script src="{{asset('assets/vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

<!-- Page level custom scripts -->
<script src="{{asset('assets/js/demo/datatables-demo.js')}}"></script>
@endsection