routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\ElectricityController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ClientDetailController;
use App\Http\Controllers\MaintenanceController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\BuildingController;
use App\Http\Controllers\AreaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::get('/ajax/cancel_booking', [HomeController::class, 'getCancelBooking']);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    // Admin Setting
    Route::resource('roles', RoleController::class)->names([
        'index' => 'admin.roles.index',
        'create' => 'admin.roles.create',
        'edit' => 'admin.roles.edit',
        'destroy' => 'admin.roles.destroy',
        // Add other routes if needed
    ]);
    Route::resource('users', UserController::class)->names([
        'index' => 'admin.users.index',
        'create' => 'admin.users.create',
        // Add other routes if needed
    ]);
    Route::resource('permissions', PermissionController::class)->names([
        'index' => 'admin.permissions.index',
        'create' => 'admin.permissions.create',
        // Add other routes if needed
    ]);
    Route::resource('rooms', RoomController::class)->names([
        'index' => 'admin.rooms.index',
        'create' => 'admin.rooms.create',
    ]);
    Route::resource('electricities', ElectricityController::class);
    Route::resource('clients', ClientController::class);
    Route::post('checkout-client', [ClientController::class,'checkout'])->name('checkout-client');
    Route::resource('client-details', ClientDetailController::class);
    Route::resource('maintenances', MaintenanceController::class);
    Route::resource('expenses', ExpenseController::class);
    Route::resource('areas', AreaController::class);
    Route::resource('buildings', BuildingController::class);
    Route::get('client-details-create/{id}', [ClientDetailController::class,'billing'])->name('client-details-create');
    Route::get('client-details-view/{id}', [ClientDetailController::class,'billingDetail'])->name('client-details-view');
    Route::get('client-details-download/{id}', [ClientDetailController::class,'billingDownload'])->name('client-details-download');
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
    Route::get('/calculate-eb-amount', [ClientDetailController::class, 'calculateEbAmount'])->name('calculate.eb.amount');

    // End Admin Setting
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Client extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'room_id',
        'name',
        'mobile',
        'email',
        'photo',
        'client_id',
        'father_name',
        'occupation',
        'residential_address',
        'id_proof_type',
        'id_proof_number',
        'property_id',
        'id_proof_photo',
        'address',
        'deposit',
        'booking_date',
        'status',
        'created_by'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'deleted_at' => 'datetime',
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Storage; // Import Storage facade
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Client;
use App\Models\User;
use App\Models\Room;
use App\Models\CheckoutDetail;
use Spatie\Permission\Models\Permission;
use DB;
use Auth;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:client-list');
         $this->middleware('permission:client-create', ['only' => ['create','store']]);
         $this->middleware('permission:client-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:client-delete', ['only' => ['destroy']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user   = Auth::user();
        // $query  = Client::withTrashed()->orderBy('id','DESC');
        $query  = Client::orderBy('id','DESC');
        if(isset($request->search))
        {
            if(isset($request->fromdate))
            {
                if($request->fromdate!=""){
                    $Sindate= date("Y-m-d", strtotime($request->fromdate));
                    $query->where('clients.created_at','>=',$Sindate);
                } 
            }
            if(isset($request->todate))
            {
                if($request->todate!=""){
                    $Todate= date("Y-m-d", strtotime($request->todate. ' +1 day'));
                    $query->where('clients.created_at','<=',$Todate);
                }  
            }
           
            if($request->name)
            {
                $name=$request->name;
                $query->where('clients.name','like', '%'.$name.'%');
            }
        }
        $clients = $query->paginate(20);
        return view('admin.clients.index',compact('clients','request'))
            ->with('i', ($request->input('page', 1) - 1) * 20);
       
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $rooms = Room::all()->filter(function($room) {
            return ClientController::getRoomCount($room->id) == 1;
        });
        // $rooms  =   Room::where('status',1)->pluck('name','id');
        return view('admin.clients.create',compact('rooms'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'                      =>  'required|string|max:255',
            'email'                     =>  'required|email|max:255',
            'mobile'                    =>  'required|digits:10',
            'occupation'                =>  'required|string|max:255',
            'id_proof_number'           =>  'required|string|max:255',
            'room_id'                   =>  'required|exists:rooms,id',
            'residential_address'       =>  'required|string|max:1000',
            'father_name'               =>  'required|string|max:255',
            'id_proof_type'             =>  'required|string|in:Student ID,Passport,Driving License,Aadhar Card,Ration card,Voter ID',
            'deposit'                   =>  'required|numeric|min:0',
            'address'                   =>  'required|string|max:1000',
            'photo'                     =>  'required|image|mimes:jpeg,png,jpg|max:1024',
            'id_proof_photo'            =>  'required|image|mimes:jpeg,png,jpg|max:1024',
        ]);     
        
        $inputs                 =   $request->all();
        $inputs['created_by']   =   Auth::user()->id;
        $inputs['status']       =   4;
        //  Handle photo upload
        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $photoName = uniqid() . '.' . $photo->getClientOriginalExtension();
            $path = Storage::putFileAs('public/photos', $photo, $photoName);
            $inputs['photo'] = basename($path);
        }

        // Handle ID proof photo upload
        if ($request->hasFile('id_proof_photo')) {
            $idProofPhoto = $request->file('id_proof_photo');
            $idProofPhotoName = uniqid() . '.' . $idProofPhoto->getClientOriginalExtension();
            $path = Storage::putFileAs('public/photo_copy', $idProofPhoto, $idProofPhotoName);
            $inputs['id_proof_photo'] = basename($path);
        }
        $clients                =   Client::create($inputs);
        $client_id              =   $request->room_id . date('Y') . $clients->id;
        $clients->update(['client_id' => $client_id]);
        $inputs['property_id']  =   Auth::user()->property_id;
        $clients->save();
        return redirect()->route('clients.index')->with('success','Client created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $client     =   Client::find($id);
        $user       =   User::pluck('name','id');
        $rooms      =   Room::where('status',1)->pluck('name','id');
        return view('admin.clients.show',compact('client','rooms','user'));
    }

    public function checkout(Request $request)
    {
        $request->validate([
            'return_deposit'    =>  'required',
            'reason'            =>  'required',
            'checkout_date'     =>  'required',
        ]);     
        
        $inputs['return_deposit']   =   $request->return_deposit;
        $inputs['reason']           =   $request->reason;
        $inputs['checkout_date']    =   $request->checkout_date;
        $inputs['client_id']        =   $request->client_id;
        $inputs['created_by']       =   Auth::user()->id;
        CheckoutDetail::create($inputs);
        $update                     =   Client::find($request->client_id)->update(['status'=>4]);
        return redirect()->back()->with('success','Checkout SucessFully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client     =   Client::find($id);
        $user       =   User::pluck('name','id');
        $rooms = Room::all()->filter(function($room) {
            return ClientController::getRoomCount($room->id) == 1;
        });
        // $rooms      =   Room::where('status',1)->pluck('name','id');
        return view('admin.clients.edit',compact('client','user','rooms'));
        
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
{
    // Validate the request
    $request->validate([
        'name'                  =>  'required|string|max:255',
        'email'                 =>  'required|email|max:255',
        'mobile'                =>  'required|digits:10',
        'occupation'            =>  'required|string|max:255',
        'id_proof_number'       =>  'required|string|max:255',
        'room_id'               =>  'required|exists:rooms,id',
        'residential_address'   =>  'required|string|max:255',
        'father_name'           =>  'required|string|max:255',
        'id_proof_type'         =>  'required|string|max:255',
        'deposit'               =>  'required|numeric',
        'address'               =>  'required|string|max:255',
        'photo'                 =>  'nullable|image|mimes:jpg,jpeg,png|max:1024', // 1MB Max
        'id_proof_photo'        =>  'nullable|image|mimes:jpg,jpeg,png|max:1024', // 1MB Max
    ]);

    // Find the client by ID
    $client = Client::findOrFail($id);

    // Update client data
    $client->name = $request->input('name');
    $client->email = $request->input('email');
    $client->mobile = $request->input('mobile');
    $client->occupation = $request->input('occupation');
    $client->id_proof_number = $request->input('id_proof_number');
    $client->room_id = $request->input('room_id');
    $client->residential_address = $request->input('residential_address');
    $client->father_name = $request->input('father_name');
    $client->id_proof_type = $request->input('id_proof_type');
    $client->deposit = $request->input('deposit');
    $client->address = $request->input('address');

    // Handle file uploads
    if ($request->hasFile('photo')) {
        // Delete the old photo if exists
        if ($client->photo) {
            Storage::delete('public/photos' . $client->photo);
        }
        // Delete the old photo if it exists
        if ($client->photo) {
            $photoPath = 'public/photos/' . $client->photo;

            // Check if the file exists before attempting deletion
            if (Storage::exists($photoPath)) {
                Storage::delete($photoPath);
            }
        }

        // Store the new photo
        $photoPath = $request->file('photo')->store('photos', 'public');
        $client->photo = $photoPath;
    }

    if ($request->hasFile('id_proof_photo')) {
        // Delete the old ID proof photo if exists
        if ($client->id_proof_photo) {
            Storage::delete('public/photo_copy' . $client->id_proof_photo);
        }
        // Store the new ID proof photo
        $idProofPhotoPath = $request->file('id_proof_photo')->store('photo_copy', 'public');
        $client->id_proof_photo = $idProofPhotoPath;
    }

    // Save the client
    $client->save();

    // Redirect back with success message

resources/views/admin/clients/edit.blade.php
@extends('layouts.master')

@php 
$page_title = 'Client Edit'; 
$page_name = 'Client Edit'; 
@endphp 

@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css" rel="stylesheet" />
@endsection 

@section('content')
<div class="container-fluid">
    @if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif 

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">Edit Client</h6>
            <a href="{{ route('clients.index') }}">
                <button type="button" class="btn btn-danger" id="cancelButton">Back</button>
            </a>
        </div>
        <div class="card-body">
            <form method="POST" action="{{ route('clients.update', $client->id) }}" id="clientCreation" enctype="multipart/form-data">
                @csrf @method('PUT')
                <div class="form-row">
                    <div class="col-lg-8">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="mb-3">
                                    <label for="name">Name</label>
                                    <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $client->name) }}" placeholder="Client Name"/>
                                </div>
                                <div class="mb-3">
                                    <label for="email">Email</label>
                                    <input type="email" class="form-control" id="email" name="email" value="{{ old('email', $client->email) }}" placeholder="Email"/>
                                </div>
                                <div class="mb-3">
                                    <label for="occupation">Occupation</label>
                                    <input type="text" class="form-control" id="occupation" name="occupation" value="{{ old('occupation', $client->occupation) }}" placeholder="Occupation"/>
                                </div>
                                <div class="mb-3">
                                    <label for="id_proof_number">Id Proof Number</label>
                                    <input type="text" class="form-control" id="id_proof_number" name="id_proof_number" value="{{ old('id_proof_number', $client->id_proof_number) }}" placeholder="ID Proof Number"/>
                                </div>
                                <div class="mb-3">
                                    <label for="residential_address">Residential Address</label>
                                    <textarea class="form-control" name="residential_address" id="residential_address" rows="4" placeholder="Enter The Residential Address..">{{ old('residential_address', $client->residential_address) }}</textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="room_id">Room</label>
                                    {!! Form::select('room_id', $rooms->pluck('name', 'id'), old('room_id'), ['class' => 'form-control', 'id' => 'room_id', 'placeholder' => 'Select Room']) !!}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="mb-3">
                                    <label for="mobile">Mobile</label>
                                    <input type="text" class="form-control" id="mobile" name="mobile" value="{{ old('mobile', $client->mobile) }}" placeholder="Mobile"/>
                                </div>
                                <div class="mb-3">
                                    <label for="father_name">Father Name</label>
                                    <input type="text" class="form-control" id="father_name" name="father_name" value="{{ old('father_name', $client->father_name) }}" placeholder="Father Name"/>
                                </div>
                                <div class="mb-3">
                                    <label for="id_proof_type">Id Proof Type</label>
                                    <select name="id_proof_type" class="form-control" id="id_proof_type">
                                        <option value="">--select Type--</option>
                                        <option value="Student ID" {{ old('id_proof_type', $client->id_proof_type) == 'Student ID' ? 'selected' : '' }}>Student ID</option>
                                        <option value="Passport" {{ old('id_proof_type', $client->id_proof_type) == 'Passport' ? 'selected' : '' }}>Passport</option>
                                        <option value="Driving License" {{ old('id_proof_type', $client->id_proof_type) == 'Driving License' ? 'selected' : '' }}>Driving License</option>
                                        <option value="Aadhar Card" {{ old('id_proof_type', $client->id_proof_type) == 'Aadhar Card' ? 'selected' : '' }}>Aadhar Card</option>
                                        <option value="Ration card" {{ old('id_proof_type', $client->id_proof_type) == 'Ration card' ? 'selected' : '' }}>Ration card</option>
                                        <option value="Voter ID" {{ old('id_proof_type', $client->id_proof_type) == 'Voter ID' ? 'selected' : '' }}>Voter ID</option>
                                    </select>
                                </div>
                                <div class="mb-3">
                                    <label for="deposit">Deposit</label>
                                    <input type="text" class="form-control" id="deposit" name="deposit" value="{{ old('deposit', $client->deposit) }}" placeholder="Deposit"/>
                                </div>
                                <div class="mb-3">
                                    <label for="address">Address</label>
                                    <textarea class="form-control" name="address" id="address" rows="4" placeholder="Enter The Address..">{{ old('address', $client->address) }}</textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="deposit">Client ID</label>
                                    <input type="text" class="form-control" id="client_id" name="client_id" value="{{ old('client_id', $client->client_id) }}" placeholder="Client Id" readonly/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="mb-3">
                            <label for="photo">Client Photo</label>
                            <input type="file" id="photo" name="photo" class="dropify" data-default-file="{{ $client->photo ? asset('storage/' . $client->photo) : 'path_to_default_image' }}" />
                            <div id="photo_error" class="invalid-feedback d-block">{{ $errors->first('photo') }}</div>
                        </div>
                        <div class="mb-3">
                            <label for="id_proof_photo">Id Proof Photo</label>
                            <input type="file" id="id_proof_photo" name="id_proof_photo" class="dropify" data-default-file="{{ $client->id_proof_photo ? asset('storage/' . $client->id_proof_photo) : 'path_to_default_image' }}" />
                            <div id="id_proof_photo_error" class="invalid-feedback d-block">{{ $errors->first('id_proof_photo') }}</div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection 

@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js"></script>
<script>
    $(document).ready(function () {
        $("#clientCreation").validate({
            rules: {
                name: "required",
                email: {
                    required: true,
                    email: true
                },
                mobile: {
                    required: true,
                    digits: true,
                    minlength: 10,
                    maxlength: 10
                },
                occupation: "required",
                id_proof_number: "required",
                room_id: "required",
                residential_address: "required",
                father_name: "required",
                id_proof_type: "required",
                deposit: {
                    required: true,
                    digits: true
                },
                address: "required",
                // photo: {
                //     required: true,
                //     extension: "jpg|jpeg|png",
                //     filesize: 1048576 // 1MB in bytes
                // },
                // id_proof_photo: {
                //     required: true,
                //     extension: "jpg|jpeg|png",
                //     filesize: 1048576 // 1MB in bytes
                // }
            },
            messages: {
                name: "Please enter the client's name",
                email: {
                    required: "Please enter the client's email",
                    email: "Please enter a valid email address"
                },
                mobile: {
                    required: "Please enter the client's mobile number",
                    digits: "Please enter only digits",
                    minlength: "Mobile number should be 10 digits",
                    maxlength: "Mobile number should be 10 digits"
                },
                occupation: "Please enter the client's occupation",
                id_proof_number: "Please enter the ID proof number",
                room_id: "Please select a room",
                residential_address: "Please enter the residential address",
                father_name: "Please enter the father's name",
                id_proof_type: "Please select the ID proof type",
                deposit: {
                    required: "Please enter the deposit amount",
                    digits: "Please enter a valid number"
                },
                address: "Please enter the address",
                // photo: {
                //     required: "Please upload a client photo",
                //     extension: "Only JPEG and PNG files are allowed",
                //     filesize: "File size must be less than 1MB"
                // },
                // id_proof_photo: {
                //     required: "Please upload an ID proof photo",
                //     extension: "Only JPEG and PNG files are allowed",
                //     filesize: "File size must be less than 1MB"
                // }
            },
            errorPlacement: function(error, element) {
                if (element.attr("name") == "photo") {
                    error.appendTo("#photo_error");
                } else if (element.attr("name") == "id_proof_photo") {
                    error.appendTo("#id_proof_photo_error");
                } else {
                    error.insertAfter(element);
                }
            }
        });

        $(".dropify").dropify({
            messages: {
                default: "Drag and drop a file here or click",
                replace: "Drag and drop or click to replace",
                remove: "Remove",
                error: "Oops! Something went wrong. Please try again.",
                imgPlaceholder: "Click to upload image",
            },
            error: {
                fileSize: "The file size is too big (max 1MB).",
                fileExtension: "Only image files (jpg, jpeg, png) are allowed.",
            },
            maxFileSize: "1M",
            allowedFileExtensions: ["jpg", "jpeg", "png"],
            tpl: {
                wrap: '<div class="dropify-wrapper"></div>',
                loader: '<div class="dropify-loader"></div>',
                message: '<div class="dropify-message"><span class="file-icon" /></div>',
                preview: '<div class="dropify-preview"><span class="dropify-render"></span></div>',
                filename: '<div class="dropify-filename"><span class="file-icon" /></div>',
                clearButton: '<button type="button" class="dropify-clear">Remove</button>',
                errorLine: '<div class="dropify-error"></div>',
                errorsContainer: '<div class="dropify-errors-container"><ul></ul></div>',
            },
        });

        $.validator.addMethod("extension", function(value, element, param) {
            param = typeof param === "string" ? param.replace(/,/g, '|') : "png|jpe?g";
            return this.optional(element) || value.match(new RegExp(".(" + param + ")$", "i"));
        }, $.validator.format("Please enter a valid extension."));

        $.validator.addMethod("filesize", function(value, element, param) {
            return this.optional(element) || (element.files[0].size <= param);
        }, $.validator.format("File size must be less than {0} bytes."));
    });
</script>
@endsection