routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\ElectricityController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ClientDetailController;
use App\Http\Controllers\MaintenanceController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\BuildingController;
use App\Http\Controllers\AreaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::get('/ajax/cancel_booking', [HomeController::class, 'getCancelBooking']);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    // Admin Setting
    Route::resource('roles', RoleController::class)->names([
        'index' => 'admin.roles.index',
        'create' => 'admin.roles.create',
        'edit' => 'admin.roles.edit',
        'destroy' => 'admin.roles.destroy',
        // Add other routes if needed
    ]);
    Route::resource('users', UserController::class)->names([
        'index' => 'admin.users.index',
        'create' => 'admin.users.create',
        // Add other routes if needed
    ]);
    Route::resource('permissions', PermissionController::class)->names([
        'index' => 'admin.permissions.index',
        'create' => 'admin.permissions.create',
        // Add other routes if needed
    ]);
    Route::resource('rooms', RoomController::class)->names([
        'index' => 'admin.rooms.index',
        'create' => 'admin.rooms.create',
    ]);
    Route::resource('electricities', ElectricityController::class);
    Route::resource('clients', ClientController::class);
    Route::post('checkout-client', [ClientController::class,'checkout'])->name('checkout-client');
    Route::resource('client-details', ClientDetailController::class);
    Route::resource('maintenances', MaintenanceController::class);
    Route::resource('expenses', ExpenseController::class);
    Route::resource('areas', AreaController::class);
    Route::resource('buildings', BuildingController::class);
    Route::get('client-details-create/{id}', [ClientDetailController::class,'billing'])->name('client-details-create');
    Route::get('client-details-view/{id}', [ClientDetailController::class,'billingDetail'])->name('client-details-view');
    Route::get('client-details-download/{id}', [ClientDetailController::class,'billingDownload'])->name('client-details-download');
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
    Route::get('/calculate-eb-amount', [ClientDetailController::class, 'calculateEbAmount'])->name('calculate.eb.amount');

    // End Admin Setting
});

app/Models/Area.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Area extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'pincode',
        'created_by',
        'status'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'deleted_at' => 'datetime',
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AreaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Area;
use App\Models\User;
use Spatie\Permission\Models\Permission;
use DB;
use Auth;

class AreaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:area-list');
         $this->middleware('permission:area-create', ['only' => ['create','store']]);
         $this->middleware('permission:area-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:area-delete', ['only' => ['destroy']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user   = Auth::user();
        // $query  = Area::withTrashed()->orderBy('id','DESC');
        $query  = Area::orderBy('id','DESC');
        if(isset($request->search))
        {
            if(isset($request->fromdate))
            {
                if($request->fromdate!=""){
                    $Sindate= date("Y-m-d", strtotime($request->fromdate));
                    $query->where('areas.created_at','>=',$Sindate);
                } 
            }
            if(isset($request->todate))
            {
                if($request->todate!=""){
                    $Todate= date("Y-m-d", strtotime($request->todate. ' +1 day'));
                    $query->where('areas.created_at','<=',$Todate);
                }  
            }
           
            if($request->name)
            {
                $name=$request->name;
                $query->where('areas.name','like', '%'.$name.'%');
            }
        }
        $areas = $query->paginate(20);
        return view('admin.areas.index',compact('areas','request'))
            ->with('i', ($request->input('page', 1) - 1) * 20);
       
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.areas.create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'      => 'required|unique:areas,name',
            'pincode'   => 'required', // adjust 10 to the maximum length you need
        ]);
        $inputs                 =   $request->all();
        $inputs['created_by']   =   Auth::user()->id;
        $areas                  =   Area::create($inputs);
        return redirect()->route('areas.index')->with('success','Area created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $area               =   Area::find($id);
        return view('admin.areas.index',compact('area'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $area    =   Area::find($id);
        $user    =   User::pluck('name','id');
        return view('admin.areas.edit',compact('area','user'));
        
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'      => 'required|unique:areas,name,' . $id,
            'pincode'   => 'required', // Adjust based on your requirements
        ]);
        $area           =   Area::findOrFail($id);
        $area->name     =   $request->input('name');
        $area->pincode  =   $request->input('pincode');
        $area->status   =   $request->input('status');
        $area->save();
        return redirect()->route('areas.index')->with('success', 'Area updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Area $area)
    {
        $area->delete();
        return redirect()->route('areas.index')->with('success','Area deleted successfully');
        
    }
}

resources/views/admin/areas/create.blade.php
@extends('layouts.master') @php $page_title = 'Area Booking'; $page_name = 'Area Booking'; @endphp @section('css')
<link rel="stylesheet" href="{{ asset('assets/css/datepicker.min.css') }}" />
@endsection @section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <!-- <h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.
        </p> -->

    <!-- DataTales Example -->
    @if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">Add Area</h6>
            <a href="{{ route('areas.index') }}">
                <button type="button" class="btn btn-danger" id="cancelButton">Back</button>
            </a>
        </div>
        <div class="card-body">
            <form method="POST" action="{{ route('areas.store') }}" id="areaCreation">
                @csrf
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="inputCity">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{old('name')}}" placeholder="Area Name"/>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputCity">Pincode</label>
                        <input type="text" class="form-control" id="pincode" name="pincode" value="{{old('pincode')}}" placeholder="Pincode"/>
                    </div>
                </div>
               
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection @section('js')
<!-- Page level plugins -->

<!-- Page level custom scripts -->
<script src="{{ asset('assets/js/datepicker.min.js') }}"></script>
<script>
    $(document).ready(function () {
        $("#areaCreation").validate({
            rules: {
                name: "required",
                pincode: {
                    required: true,
                    digits: true,
                },
            },
            messages: {
                name: "Please Enter Name",
                pincode: {
                    required: "This field is required",
                    digits: "Please enter only digits",
                },
            }
        });
    });
</script>
@endsection

resources/views/admin/areas/edit.blade.php
@extends('layouts.master') @php $page_title = 'Area Booking'; $page_name = 'Area Booking'; @endphp @section('css')
<link rel="stylesheet" href="{{ asset('assets/css/datepicker.min.css') }}" />
@endsection @section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <!-- <h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.
        </p> -->

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">Edit Area</h6>
            <a href="{{ route('areas.index') }}">
                <button type="button" class="btn btn-danger" id="cancelButton">Back</button>
            </a>
        </div>

        <div class="card-body">
            <form method="POST" action="{{ route('areas.update', $area->id) }}" id="areaCreation">
                @csrf @method('PUT')
                <input type="hidden" value="{{ $area->id }}" name="area_id" id="area_id" />
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="inputCity">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $area->name) }}" placeholder="Area Name" />
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputCity">Pincode</label>
                        <input type="text" class="form-control" id="pincode" name="pincode" value="{{old('pincode',$area->pincode)}}" placeholder="Pincode"/>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputCity">Status</label>
                        <select name="status" class="form-control" id="status">
                            <option value="">--select Status--</option>
                            <option value="1" {{ old('status', $area->status ?? '') == "1" ? 'selected' : '' }}>Active</option>
                            <option value="2" {{ old('status', $area->status ?? '') == "2" ? 'selected' : '' }}>Inactive</option>
                        </select>
                    </div>
                </div>
                <div class="form-row">
                    @if($area->creted_by!='')
                        <div class="form-group col-md-4">
                            <label for="inputCity">Created By</label>
                            <input type="text" class="form-control"  value="{{$user[$area->creted_by] ?? ''}}" readonly/>
                        </div>
                    @endif
                    
                </div>
                <!-- <button type="submit" class="btn btn-primary">Submit</button> -->
            </form>
        </div>
    </div>
</div>
@endsection @section('js')
<!-- Page level plugins -->
<script src="{{asset('assets/vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

<!-- Page level custom scripts -->
<script src="{{asset('assets/js/demo/datatables-demo.js')}}"></script>
<script src="{{ asset('assets/js/datepicker.min.js') }}"></script>
<script>
    $(document).ready(function () {
        $("#areaCreation").validate({
            rules: {
                name: "required",
                amount: {
                    required: true,
                    digits: true,
                },
            },
            messages: {
                name: "Please Enter Name",
                amount: {
                    required: "This field is required",
                    digits: "Please enter only digits",
                },
            }
        });
    });
</script>
@endsection

resources/views/admin/areas/index.blade.php
@extends('layouts.master') @php $page_title = 'All Area-List'; $page_name = 'All Area-List'; @endphp @section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <!-- <h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.
        </p> -->

    <!-- DataTales Example -->
    @if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">All Area</h6>
            <a href="{{ route('areas.create') }}">
                <button type="button" class="btn btn-success" id="cancelButton">Add New</button>
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>S.no</th>
                            <th>Name</th>
                            <th>Pincode</th>
                            <th>Status</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>S.no</th>
                            <th>Name</th>
                            <th>Pincode</th>
                            <th>Status</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach($areas as $area)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{$area->name ?? ''}}</td>
                            <td>{{$area->pincode ?? ''}}</td>
                            <td>{!! $area->status == 1 ? '<span class="badge bg-success">Active</span> ' :'<span class="badge bg-danger">InActive</span>' !!}</td>
                            <td>{{$area->created_at ? date('d M-y',strtotime($area->created_at)) : ''}}</td>
                            <td>
                                <a href="{{ route('areas.edit',$area->id) }}" class="btn btn-warning btn-sm keychainify-checked"><i class="fas fa-pen-square fa-fw"></i></a>
                                {!! Form::open(['method' => 'DELETE','route' => ['areas.destroy', $area->id],'style'=>'display:inline']) !!}
                                <button type="submit" style="border: 0px;" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-danger btn-sm"><i class="fas fa-trash fa-fw"></i></button>
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection @section('js')
<!-- Page level plugins -->
<script src="{{asset('assets/vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

<!-- Page level custom scripts -->
<script src="{{asset('assets/js/demo/datatables-demo.js')}}"></script>
@endsection