routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\ElectricityController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ClientDetailController;
use App\Http\Controllers\MaintenanceController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\BuildingController;
use App\Http\Controllers\AreaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::get('/ajax/cancel_booking', [HomeController::class, 'getCancelBooking']);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    // Admin Setting
    Route::resource('roles', RoleController::class)->names([
        'index' => 'admin.roles.index',
        'create' => 'admin.roles.create',
        'edit' => 'admin.roles.edit',
        'destroy' => 'admin.roles.destroy',
        // Add other routes if needed
    ]);
    Route::resource('users', UserController::class)->names([
        'index' => 'admin.users.index',
        'create' => 'admin.users.create',
        // Add other routes if needed
    ]);
    Route::resource('permissions', PermissionController::class)->names([
        'index' => 'admin.permissions.index',
        'create' => 'admin.permissions.create',
        // Add other routes if needed
    ]);
    Route::resource('rooms', RoomController::class)->names([
        'index' => 'admin.rooms.index',
        'create' => 'admin.rooms.create',
    ]);
    Route::resource('electricities', ElectricityController::class);
    Route::resource('clients', ClientController::class);
    Route::post('checkout-client', [ClientController::class,'checkout'])->name('checkout-client');
    Route::resource('client-details', ClientDetailController::class);
    Route::resource('maintenances', MaintenanceController::class);
    Route::resource('expenses', ExpenseController::class);
    Route::resource('areas', AreaController::class);
    Route::resource('buildings', BuildingController::class);
    Route::get('client-details-create/{id}', [ClientDetailController::class,'billing'])->name('client-details-create');
    Route::get('client-details-view/{id}', [ClientDetailController::class,'billingDetail'])->name('client-details-view');
    Route::get('client-details-download/{id}', [ClientDetailController::class,'billingDownload'])->name('client-details-download');
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
    Route::get('/calculate-eb-amount', [ClientDetailController::class, 'calculateEbAmount'])->name('calculate.eb.amount');

    // End Admin Setting
});

app/Models/Maintenance.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Maintenance extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'reason',
        'property_id',
        'amount',
        'paid_amount',
        'photo_copy',
        'date',
        'status',
        'created_by'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'deleted_at' => 'datetime',
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/MaintenanceController.php
<?php

namespace App\Http\Controllers;

use Barryvdh\DomPDF\Facade;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Maintenance;
use Spatie\Permission\Models\Permission;
use DB;
use Auth;
use PDF;

class MaintenanceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:maintenance-list');
         $this->middleware('permission:maintenance-create', ['only' => ['create','store']]);
         $this->middleware('permission:maintenance-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:maintenance-delete', ['only' => ['destroy']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user   = Auth::user();
        $query  = Maintenance::orderBy('id','DESC');
        if(isset($request->search))
        {
            if(isset($request->fromdate))
            {
                if($request->fromdate!=""){
                    $Sindate= date("Y-m-d", strtotime($request->fromdate));
                    $query->where('maintenances.created_at','>=',$Sindate);
                } 
            }
            if(isset($request->todate))
            {
                if($request->todate!=""){
                    $Todate= date("Y-m-d", strtotime($request->todate. ' +1 day'));
                    $query->where('maintenances.created_at','<=',$Todate);
                }  
            }
           
            if($request->name)
            {
                $name=$request->name;
                $query->where('maintenances.name','like', '%'.$name.'%');
            }
        }
        $maintenances = $query->paginate(20);
        return view('admin.maintenances.index',compact('maintenances','request'))
            ->with('i', ($request->input('page', 1) - 1) * 20);
       
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        return view('admin.maintenances.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'date' => 'required'
        ], [
            'name.required' => 'Please enter the Name.',
            'date.required' => 'Please enter the Date.',
        ]);
        $inputs                 =   $request->all();
        $inputs['created_by']   =   Auth::user()->id;
        $inputs['property_id']  =   Auth::user()->property_id;
        //  Handle photo upload
        if ($request->hasFile('photo_copy')) {
            $photo = $request->file('photo_copy');
            $photoName = uniqid() . '.' . $photo->getClientOriginalExtension();
            $path = Storage::putFileAs('public/photo_copy', $photo, $photoName);
            $inputs['photo_copy'] = basename($path);
        }
        $maintenances           =   Maintenance::create($inputs);
        return redirect()->route('maintenances.index')->with('success','Maintenance created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $maintenance    =   Maintenance::pluck('id','name');
        return view('admin.maintenances.show',compact('client','maintenance','client_details'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $maintenance    =   Maintenance::find($id);
        return view('admin.maintenances.edit',compact('maintenance'));
        
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'      => 'required',
            'date'    => 'required'
        ]);
        $maintenance            =   Maintenance::findOrFail($id);
        $maintenance->name      =   $request->input('name');
        $maintenance->date      =   $request->input('date');
        // Handle file uploads
    if ($request->hasFile('photo_copy')) {
        // Delete the old photo if exists
        if ($maintenance->photo_copy) {
            Storage::delete('public/photo_copy' . $maintenance->photo_copy);
        }
        // Delete the old photo if it exists
        if ($maintenance->photo_copy) {
            $photoPath = 'public/photos/' . $maintenance->photo_copy;

            // Check if the file exists before attempting deletion
            if (Storage::exists($photoPath)) {
                Storage::delete($photoPath);
            }
        }

        // Store the new photo
        $photoPath = $request->file('photo_copy')->store('photo_copy', 'public');
        $maintenance->photo_copy = $photoPath;
    }
        $maintenance->save();
        return redirect()->route('maintenances.index')->with('success', 'Maintenance updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Maintenance $maintenance)
    {
        $maintenance->delete();
        return redirect()->route('admin.maintenances.index')->with('success','Maintenance deleted successfully');
        
    }
}

resources/views/admin/maintenances/create.blade.php
@extends('layouts.master') @php $page_title = 'Maintenance || Addnew'; $page_name = 'Maintenance || Addnew'; @endphp @section('css')
<link rel="stylesheet" href="{{ asset('assets/css/datepicker.min.css') }}" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css" rel="stylesheet" />
@endsection @section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <!-- <h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.
        </p> -->

    <!-- DataTales Example -->
    @if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">Add Maintenance</h6>
            <a href="{{ route('maintenances.index') }}">
                <button type="button" class="btn btn-danger" id="cancelButton">Back</button>
            </a>
        </div>
        <div class="card-body">
            <form method="POST" action="{{ route('maintenances.store') }}" id="maintenanceCreation" enctype="multipart/form-data">
                @csrf
                <div class="form-row">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="inputCity">Title</label>
                                    <input type="text" class="form-control" id="name" name="name" value="{{old('name')}}" placeholder="Title" />
                                </div>
                                <div class="mb-3">
                                    <label for="inputCity">Amount</label>
                                    <input type="text" class="form-control" id="amount" name="amount" value="{{old('amount')}}" placeholder="Amount" />
                                    <div class="mb-3">
                                        <label for="date">Date</label>
                                        <input type="text" autocomplete="off" name="date" id="date" placeholder="Date" class="form-control air-datepicker" data-date-format="yyyy-mm-dd" value="{{ old('date') }}" readonly />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="inputCity">Reason</label>
                                    <input type="text" class="form-control" id="reason" name="reason" value="{{old('reason')}}" placeholder="Reason" />
                                </div>
                                <div class="mb-3">
                                    <label for="inputCity">Paid Amount</label>
                                    <input type="text" class="form-control" id="paid_amount" name="paid_amount" value="{{old('paid_amount')}}" placeholder="Paid Amount" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="mb-3">
                            <label for="photo_copy">Bill Photo Copy</label>
                            <input type="file" id="photo_copy" name="photo_copy" class="dropify" data-default-file="path_to_default_image" />
                            <div id="photo_copy_error" class="invalid-feedback d-block">{{ $errors->first('photo') }}</div>
                            <div id="profile_image_error" class="invalid-feedback"></div>
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection @section('js')
<!-- Page level plugins -->

<!-- Page level custom scripts -->
<script src="{{ asset('assets/js/datepicker.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js"></script>
<script>
    if ($.fn.datepicker !== undefined) {
        $(".air-datepicker").datepicker({
            language: {
                days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
                daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
                daysMin: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
                months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
                monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                today: "Today",
                clear: "Clear",
                dateFormat: "Y-m-d",
                firstDay: 0,
            },
        });
    }
    $(document).ready(function () {
        $("#maintenanceCreation").validate({
            rules: {
                name: "required",
                reason: "required",
                date: {
                    required: true,
                },
                amount: {
                    required: true,
                    digits: true
                },
                paid_amount: {
                    required: true,
                    digits: true
                },
            },
            messages: {
                name: "Please Enter Name",
                reason: "Please Enter Reason",
                date: {
                    required: "Please Select Type",
                },
                amount: {
                    required: "Please enter the deposit amount",
                    digits: "Please enter a valid number"
                },
                paid_amount: {
                    required: "Please enter the deposit amount",
                    digits: "Please enter a valid number"
                }
            },
        });
    });
    $(".dropify").dropify({
        messages: {
            default: "Drag and drop a file here or click",
            replace: "Drag and drop or click to replace",
            remove: "Remove",
            error: "Oops! Something went wrong. Please try again.",
            imgPlaceholder: "Click to upload image",
        },
        error: {
            fileSize: "The file size is too big (max 1MB).",
            fileExtension: "Only image files (jpg, jpeg, png) are allowed.",
        },
        maxFileSize: "1M",
        allowedFileExtensions: ["jpg", "jpeg", "png"],
        tpl: {
            wrap: '<div class="dropify-wrapper"></div>',
            loader: '<div class="dropify-loader"></div>',
            message: '<div class="dropify-message"><span class="file-icon" /></div>',
            preview: '<div class="dropify-preview"><span class="dropify-render"></span></div>',
            filename: '<div class="dropify-filename"><span class="file-icon" /></div>',
            clearButton: '<button type="button" class="dropify-clear">Remove</button>',
            errorLine: '<div class="dropify-error"></div>',
            errorsContainer: '<div class="dropify-errors-container"><ul></ul></div>',
        },
    });
</script>
@endsection

resources/views/admin/maintenances/edit.blade.php
@extends('layouts.master') @php $page_title = 'Maintenance || Edit'; $page_name = 'Maintenance || Edit'; @endphp @section('css')
<link rel="stylesheet" href="{{ asset('assets/css/datepicker.min.css') }}" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css" rel="stylesheet" />
@endsection @section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <!-- <h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.
        </p> -->

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">Edit Maintenance</h6>
            <a href="{{ route('maintenances.index') }}">
                <button type="button" class="btn btn-danger" id="cancelButton">Back</button>
            </a>
        </div>

        <div class="card-body">
            <form method="POST" action="{{ route('maintenances.update', $maintenance->id) }}" id="maintenanceCreation" enctype="multipart/form-data">
                @csrf @method('PUT')
                <div class="form-row">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="inputCity">Title</label>
                                    <input type="text" class="form-control" id="name" name="name" value="{{old('name',$maintenance->name)}}" placeholder="Title" />
                                </div>
                                <div class="mb-3">
                                    <label for="inputCity">Amount</label>
                                    <input type="text" class="form-control" id="amount" name="amount" value="{{old('amount',$maintenance->amount)}}" placeholder="Amount" />
                                    <div class="mb-3">
                                        <label for="date">Date</label>
                                        <input
                                            type="text"
                                            autocomplete="off"
                                            name="date"
                                            id="date"
                                            placeholder="Date"
                                            class="form-control air-datepicker"
                                            data-date-format="yyyy-mm-dd"
                                            value="{{ old('date',$maintenance->date) }}"
                                            readonly
                                        />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="inputCity">Reason</label>
                                    <input type="text" class="form-control" id="reason" name="reason" value="{{old('reason',$maintenance->reason)}}" placeholder="Reason" />
                                </div>
                                <div class="mb-3">
                                    <label for="inputCity">Paid Amount</label>
                                    <input type="text" class="form-control" id="paid_amount" name="paid_amount" value="{{old('paid_amount',$maintenance->paid_amount)}}" placeholder="Paid Amount" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="mb-3">
                            <label for="photo_copy">Bill Photo Copy</label>
                            <input type="file" id="photo_copy" name="photo_copy" class="dropify" data-default-file="{{ $maintenance->photo_copy ? asset('storage/' . $maintenance->photo_copy) : 'path_to_default_image' }}" />
                            <div id="photo_copy_error" class="invalid-feedback d-block">{{ $errors->first('photo') }}</div>
                            <div id="profile_image_error" class="invalid-feedback"></div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection @section('js')
<!-- Page level plugins -->
<script src="{{ asset('assets/js/datepicker.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js"></script>
<script>
    if ($.fn.datepicker !== undefined) {
        $(".air-datepicker").datepicker({
            language: {
                days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
                daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
                daysMin: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
                months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
                monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                today: "Today",
                clear: "Clear",
                dateFormat: "Y-m-d",
                firstDay: 0,
            },
        });
    }
    $(document).ready(function () {
        $("#maintenanceCreation").validate({
            rules: {
                name: "required",
                reason: "required",
                date: {
                    required: true,
                },
                amount: {
                    required: true,
                    digits: true
                },
                paid_amount: {
                    required: true,
                    digits: true
                },
            },
            messages: {
                name: "Please Enter Name",
                reason: "Please Enter Reason",
                date: {
                    required: "Please Select Type",
                },
                amount: {
                    required: "Please enter the deposit amount",
                    digits: "Please enter a valid number"
                },
                paid_amount: {
                    required: "Please enter the deposit amount",
                    digits: "Please enter a valid number"
                }
            },
        });
    });
    $(".dropify").dropify({
        messages: {
            default: "Drag and drop a file here or click",
            replace: "Drag and drop or click to replace",
            remove: "Remove",
            error: "Oops! Something went wrong. Please try again.",
            imgPlaceholder: "Click to upload image",
        },
        error: {
            fileSize: "The file size is too big (max 1MB).",
            fileExtension: "Only image files (jpg, jpeg, png) are allowed.",
        },
        maxFileSize: "1M",
        allowedFileExtensions: ["jpg", "jpeg", "png"],
        tpl: {
            wrap: '<div class="dropify-wrapper"></div>',
            loader: '<div class="dropify-loader"></div>',
            message: '<div class="dropify-message"><span class="file-icon" /></div>',
            preview: '<div class="dropify-preview"><span class="dropify-render"></span></div>',
            filename: '<div class="dropify-filename"><span class="file-icon" /></div>',
            clearButton: '<button type="button" class="dropify-clear">Remove</button>',
            errorLine: '<div class="dropify-error"></div>',
            errorsContainer: '<div class="dropify-errors-container"><ul></ul></div>',
        },
    });
</script>
@endsection

resources/views/admin/maintenances/index.blade.php
@extends('layouts.master') @php $page_title = 'All Maintenance-List'; $page_name = 'All Maintenance-List'; @endphp @section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <!-- <h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.
        </p> -->

    <!-- DataTales Example -->
    @if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">All Maintenance</h6>
            <a href="{{ route('maintenances.create') }}">
                <button type="button" class="btn btn-success" id="cancelButton">Add New</button>
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>S.no</th>
                            <th>Title</th>
                            <th>Date</th>
                            <th>Amount</th>
                            <th>Paid Amount</th>
                            <!-- <th>Status</th> -->
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>S.no</th>
                            <th>Title</th>
                            <th>Date</th>
                            <th>Amount</th>
                            <th>Paid Amount</th>
                            <!-- <th>Status</th> -->
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach($maintenances as $maintenance)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{$maintenance->name ?? ''}}</td>
                            <td>{{$maintenance->date ? date('d M-y',strtotime($maintenance->date)) : ''}}</td>
                            <td>{{$maintenance->amount ?? ''}}</td>
                            <td>{{$maintenance->paid_amount ?? ''}}</td>
                            <!-- <td>{!! $maintenance->status == 1 ? '<span class="badge bg-success">Active</span> ' :'<span class="badge bg-danger">InActive</span>' !!}</td> -->
                            <td>{{$maintenance->created_at ? date('d M-y',strtotime($maintenance->created_at)) : ''}}</td>
                            <td>
                                <a href="{{ route('maintenances.edit',$maintenance->id) }}" class="btn btn-warning btn-sm keychainify-checked"><i class="fas fa-pen-square fa-fw"></i></a>
                                {!! Form::open(['method' => 'DELETE','route' => ['maintenances.destroy', $maintenance->id],'style'=>'display:inline']) !!}
                                <button type="submit" style="border: 0px;" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-danger btn-sm"><i class="fas fa-trash fa-fw"></i></button>
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection @section('js')
<!-- Page level plugins -->
<script src="{{asset('assets/vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

<!-- Page level custom scripts -->
<script src="{{asset('assets/js/demo/datatables-demo.js')}}"></script>
@endsection